### ISSUE TITLE
Deserialize existing XML where member name is the same as member type name

### ISSUE THREAD

**Issue by StuYarrow** [ExtendedXmlSerializer/ExtendedXmlSerializer#270]
Hi,

I am trying to set up ExtendedXmlSerializer so that it can deserialise existing XML files created by XmlSerializer.  I found that ExtendedXmlSerializer throws an exception (MWE below) if I try to deserialise a collection member whose name is the same as the name of its content type.  I think this may be a known limitation and is related to #241.

When generating its own XML, ExtendedXmlSerializer inserts an exs:member attribute to disambiguate the identically named elements.  Is there any clean and simple way to work around this for existing XML that does not have the attribute?

Thanks!
Stu

```
public static class ExtendedXmlSerializerTests
{
    public static void MemberNameSameAsTypeName()
    {
        var serializer = new ConfigurationContainer()
            .EnableImplicitTyping(typeof(Container), typeof(Item))
            .Create();

        // language=XML
        const string contentPassing =
            @"<?xml version=""1.0"" encoding=""utf-8""?>
            <Container>
	            <Items>
		            <Item Name=""Name1"" />
	            </Items>
            </Container>";

        // language=XML
        const string contentFailing =
            @"<?xml version=""1.0"" encoding=""utf-8""?>
            <Container>
	            <Items>
		            <Item Name=""Name1"" />
	            </Items>
                <Item>
                    <Item Name=""Name2"" />
                </Item>
            </Container>";

        // Succedes
        var resultPassing = serializer.Deserialize<Container>(contentPassing);

        // Throws
        var resultFailing = serializer.Deserialize<Container>(contentFailing);
    }

    public class Container
    {
        public List<Item> Items { get; } = new List<Item>();

        public List<Item> Item { get; } = new List<Item>();
    }

    public class Item
    {
        [XmlAttribute]
        public string Name { get; set; }
    }
}
```

**Comment by Mike-EEE** [comment]
> When generating its own XML, ExtendedXmlSerializer inserts an exs:member attribute to disambiguate the identically named elements

Yeah, I am not happy with that at all, @StuYarrow. 😆

EXS was never intended to work with documents produced with the classic `XmlSerializer`, although we've done our best here to try to make as many scenarios work as possible.

In this case, for migrating existing XML into a format that EXS is happy with, I would suggest running it through XSLT to create the files first, and then from there, load them with EXS.

That's what strikes me as the most apparent solution here.  I will update if I think of something else.

**Comment by StuYarrow** [comment]
Thanks for clarifying, I thought that might be the case.  I think this should be easy enough to work around on my end.

**Comment by StuYarrow** [comment]
Adding for future reference: this issue appears to occur whenever a member name is the same as the name of a serialized type.  It is not limited to members with the same name as their type.

**Comment by Mike-EEE** [comment]
Sounds like this question was answered satisfactorily.  Please do feel free to re-open with a new comment or a new issue altogether if it makes sense to do so.  Closing for now.
