### ISSUE TITLE
Housekeeping

### ISSUE THREAD

**Issue by Mike-EEE** [ExtendedXmlSerializer/ExtendedXmlSerializer#272]
Going to go through some issues that have accumulated over time.

- [x] Simplify solution
- [x] Removed unused projects
- [x] Move `Samples` and `Performance` into their own solutions
- [x] Update repository URL
- [x] Solution warnings
- [x] Convert .rst files to .md files
- [x] Remove source files and replace with Nuget dependencies
- [x] Wiki

**Comment by WojciechNagorski** [comment]
I am impressed how many changes you have done. It was a great decision to make you an owner.

I realised that I have to give you more access. For example MyGet and access to article on the code project.

**Comment by Mike-EEE** [comment]
Hah!  Yeah, I didn't want to seem like I was stepping on your toes or anything before, @WojciechNagorski. 😁  Making it "official" was the right way to go.

BTW, we do not need MyGet because AppVeyor has one already, and you can name it!

https://ci.appveyor.com/nuget/extendedxmlserializer-preview

(Please be sure to enable `Include prerelease` in Nuget explorer.)
