### ISSUE TITLE
Consolidate All Extension Methods to Root

### ISSUE THREAD

**Issue by Mike-EEE** [ExtendedXmlSerializer/ExtendedXmlSerializer#274]
Along with #272 and #189, I noticed that we now have THIRTEEN different extension methods classes.  This can result to up to as many namespace declarations in a given file.

I believe we attempted to fix this near the release of v2, however we didn't have a good solution to it, and obviously we have added more.

BUT... there IS a good solution to this: Partial Classes. 😁  We can put all the extension methods delineated, partitioned, and organized by the names of their namespaces, as such:

```
ExtensionMethods.Configuration.cs
ExtensionMethods.Content.cs
ExtensionMethods.ContentModel.Conversion.cs
ExtensionMethods.ContentModel.cs
...
```

Then all the developer has to do is:

`using ExtendedXmlSerializer;`

To get them all. :D

In fact, I do not think they even have to do that... simply `new ConfigurationContainer()` will import as it is in the `ExtendedXmlSerializer.Configuration` namespace which implicitly imports whatever is directly above it.

(Update: confirmed above as correct.)

The best part about this is that it is not a breaking change.  Pretty cool. 😎

**Comment by WojciechNagorski** [comment]
good idea. It was rather our mistake in designing.

**Comment by Mike-EEE** [comment]
And by "our" you mean _my_ designing. 😆  We actually did try to do this at one point, but I hate long files and it would have been too much.  Separating them out into partial classes is the winning ticket here.

Anyways, closing for now as they are in there. 👍
