### ISSUE TITLE
Configure Release Drafter

### ISSUE THREAD

**Issue by Mike-EEE** [ExtendedXmlSerializer/ExtendedXmlSerializer#308]
Checkin' this out:
https://github.com/toolmantim/release-drafter

**Comment by WojciechNagorski** [comment]
It looks ok. I wish I could read your article about configuration of open source project. Or even whole series.

**Comment by Mike-EEE** [comment]
Yeah that's a good idea @WojciechNagorski ... I can add it to my ever-expanding list of `TODO`s. 😆

Problem is that it's a bit of a hybrid.  I really like AppVeyor... it's awesome!  But these other newer workflows like PR Labeler are GitHub Actions, which look great but AppVeyor is mature and tested.

**Comment by WojciechNagorski** [comment]
It is a normal thing that projects have more builds. Please take a look at the BenchmarkDotNet:
![image](https://user-images.githubusercontent.com/17333903/69333980-080ed080-0c5a-11ea-978c-7b7d6c3c5a52.png)
I wanted to add Travis-ci with lin and mac. It is as simple as AppVeyor. 
There is an article about this topic:
https://andrewlock.net/adding-travis-ci-to-a-net-core-app/
